@url_dev=http://localhost:3056/v1/api/
### signup

GET {{url_dev}}product/published/all
Content-Type: application/json
x-api-key: 72b17b1b43f740b8ca7f6ccc8ea3071be30102ba51e44ffca5d7fbe70c056188ee812921e9a877460ef81ea8e2b064f395035338514f71e036f1c9df5544589b
x-client-id:65aa52d532be22abb65ae566
x-rtoken-id:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWFhNTJkNTMyYmUyMmFiYjY1YWU1NjYiLCJlbWFpbCI6InNob3BjaGw4QGdtYWlsLmNvbSIsImlhdCI6MTcwNzEwMTczMCwiZXhwIjoxNzA3NzA2NTMwfQ.kw_6UeIk2lA_GIqPCD2RlfjNO0KCeoHLhU3DCDbCVNM

